color0 #141d29
color1 #fd4663
color2 #6fa2e6
color3 #7e77dd
color4 #b080d4
color5 #92b9ec
color6 #9c96e9
color7 #f2f2f3
color8 #5f6874
color9 #fd4663
color10 #6fa2e6
color11 #7e77dd
color12 #b080d4
color13 #92b9ec
color14 #9c96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #141d29
background            #141d29
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #1b2737
active_border_color   #6fa2e6
inactive_border_color #1b2737
url_color             #6fa2e6

active_tab_foreground   #101419
active_tab_background   #6fa2e6
inactive_tab_foreground #afb2b6
inactive_tab_background #1b2737
cursor_trail_color      #afb2b6
