color0 #171d26
color1 #fd4663
color2 #6794e4
color3 #6d5cd6
color4 #a866cc
color5 #93b3ec
color6 #a196e9
color7 #f2f2f3
color8 #616875
color9 #fd4663
color10 #6794e4
color11 #6d5cd6
color12 #a866cc
color13 #93b3ec
color14 #a196e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #171d26
background            #171d26
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #1f2633
active_border_color   #6794e4
inactive_border_color #1f2633
url_color             #6794e4

active_tab_foreground   #181d25
active_tab_background   #6794e4
inactive_tab_foreground #afb1b6
inactive_tab_background #1f2633
cursor_trail_color      #afb1b6
